### ISSUE TITLE
Fedora 40 GNOME reports AppFlowy crashed after closing the application (screenshot)

### ISSUE THREAD

**Issue by almereyda** [flathub/io.appflowy.AppFlowy#102]
![grafik](https://github.com/flathub/io.appflowy.AppFlowy/assets/1645308/6875219e-00c7-4f2a-bf03-743e3722c40f)

How can I debug this further?

**Comment by suntorytimed** [comment]
Not a maintainer/developer, but I usually try to run it from the CLI to see if there is more information in terms of logs:

`flatpak run io.appflowy.AppFlowy`

and it will give you some log output in the CLI.

**Comment by almereyda** [comment]
I will do so, if it happens again.

Meanwhile closing.
