### ISSUE TITLE
Short release cycles and build automation

### ISSUE THREAD

**Issue by almereyda** [flathub/io.appflowy.AppFlowy#105]
While yesterday has seen release of v0.6.0 to Flathub, today has seen release of v0.6.1, which is a rolling update to the release line v0.6.x that introduced the spaces functionality.

date | image
--- | ---
yesterday | ![grafik](https://github.com/flathub/io.appflowy.AppFlowy/assets/1645308/cbf235f9-3b74-4ce4-836f-8b49389325de)
today | ![grafik](https://github.com/flathub/io.appflowy.AppFlowy/assets/1645308/9d84f5c6-1d95-463c-a282-fe57e8302383)

We as the user community will be happy to receive the updated via Flatpak as well.

As there is a lot of constant activity throughout the AppFlowy stack quite recently, as here from AppFlowy-Cloud, it is expected that many releases will follow.

![grafik](https://github.com/flathub/io.appflowy.AppFlowy/assets/1645308/c0be3654-6b65-493c-a542-f6a870430d7c)

Does it seem suitable to investigate automating the Flathub release procedure even further, in so that new Flathub releases are built automatically (in a CI run for a prepared Pull Request?), which can be quickly reviewed?

Are there maybe even examples of such workflows in the Flathub ecosystem, which one could use as a blueprint?

---

Reference:

- [github.com/AppFlowy-IO/AppFlowy/releases/tag/v0.6.1](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/v0.6.1)

**Comment by suntorytimed** [comment]
Unfortunately the bot does take quite some time after the release and not always creates the request. For example the 0.6.2 update got released 5 hours ago and there is no pull request by the bot.
