### ISSUE TITLE
AppFlowy doesn't start on regular Ubuntu 22.04 amd64

### ISSUE THREAD

**Issue by shvetsnikita** [flathub/io.appflowy.AppFlowy#8]
Hello!

Error message is:
```
~$ flatpak run io.appflowy.AppFlowy
app_flowy: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by app_flowy)
```

**Comment by LucasXu0** [comment]
Hi, @shvetsnikita. Can you provide your system information?

**Comment by LucasXu0** [comment]
@shvetsnikita Please run this command on the terminal and take a look at which `GLIBC` version you are using.

`ldd --version`

**Comment by shvetsnikita** [comment]
It's 2.35: https://packages.ubuntu.com/jammy/libc6

**Comment by reticulis** [comment]
#7 fixes it

**Comment by LucasXu0** [comment]
Hi, @reticulis. So, just upgrade the org.freedesktop.Platform to 22.08 will solve these problems? Can you explain more details to me?

**Comment by reticulis** [comment]
> Hi, @reticulis. So, just upgrade the org.freedesktop.Platform to 22.08 will solve these problems? Can you explain more details to me?

org.freedesktop.Platform 21.08 uses glibc 2.33, your application requires glibc 2.34, so upgrade runtime to 22.08 which uses glibc 2.35 will solve this problem
