### ISSUE TITLE
Version 0.5.5 not yet released to FlatHub

### ISSUE THREAD

**Issue by suntorytimed** [flathub/io.appflowy.AppFlowy#92]
4 days ago version 0.5.5 got released but it isn't available on FlatHub yet. A more automated release would be beneficial for Linux users.

**Comment by LucasXu0** [comment]
The Flathub bot usually automatically submits a PR, but I'm not sure why it didn't automatically update this time.

**Comment by suntorytimed** [comment]
Same issue happened for 0.6.2 (see #105) and apparently for 0.6.4 now as well.
